### ISSUE TITLE
regrouping with internal ligatures

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#641]
Some neumes (possibly those with an internal ligature) have very strange regrouping behaviour, e.g. that on "vos" near the bottom of 10r. Ungrouping the neume makes the (formerly ligated) components on C4 and B3 fall a space; attempting to move the neume components up causes the first (now correctly on the C line) to be labelled as D4, and the second (which is stuck to A) to be labelled as C4; further attempts to move the second neume component result in the label for the *first* neume to continue changing without moving either neume. (Replacing the ligature seems to be impossible.)

**Comment by JRegimbal** [comment]
I can't seem to replicate the shift that occurs in the components, but I am experiencing the issue where the ligature cannot be replaced and it seems that there's some sort of feature persisting from the ligature that's causing problems.

**Comment by JRegimbal** [comment]
It seems the issue is that after ungrouping the neume the first neume component of the ligature still is set as `ligated="true"` while the second is set to `ligated="false"`. Obviously this is a bug.

**Comment by JRegimbal** [comment]
This and #635 should be working now could you check?

**Comment by annamorphism** [comment]
I think it is working now.

**Comment by JoyfulGen** [comment]
This is still happening, at least parts of the issue. The neumes don't change pitch after being ungrouped, but one neume does move, and the ligature can't be toggled anymore. It looks like this:

I present an innocuous yellow neume with a perfectly healthy ligature (from folio 158r, penultimate line):
<img width="76" alt="158r yellow boy" src="https://user-images.githubusercontent.com/83373378/121227474-986f2f00-c859-11eb-8fc7-d0bfa1595faa.png">

If I ungroup it, the lower pitch of the ligature jumps horizontally, but doesn't change pitch:
<img width="66" alt="158r yellow boy ungrouped" src="https://user-images.githubusercontent.com/83373378/121227609-bf2d6580-c859-11eb-8ae1-69d043625f25.png">

After grouping the neumes and neume components, if I select the two neumes components I want to toggle all I get is the option to group the neume components, no matter how many times I've already done so:
<img width="1346" alt="158r can't toggle yellow boy" src="https://user-images.githubusercontent.com/83373378/121227765-f13ec780-c859-11eb-90dc-6d048d52c7f3.png">

If I delete the entire neume and input and group it again, the option to toggle the neume components reappears as normal:
<img width="1360" alt="158r all is well" src="https://user-images.githubusercontent.com/83373378/121227860-0ca9d280-c85a-11eb-8b8e-bba36a653300.png">

The MEI file, downloaded when the neume components wouldn't toggle:
[158r can't toggle yellow boy.zip](https://github.com/DDMAL/Neon/files/6618409/158r.can.t.toggle.yellow.boy.zip)

**Comment by annamorphism** [comment]
This is fixed in browser (1c34e14) but still an issue in Rodan.

**Comment by kemalkongar** [comment]
Fix confirmed, closing until it reappears in Rodan once changes are pushed.

**Comment by JoyfulGen** [comment]
Testing only the Neon job on rodan staging, this issue occurred again in folio 147r. No matter how many times I grouped the neume components, the "toggle ligature" option never appeared:
<img width="1388" alt="147r reluctant orange ligature (staging)" src="https://user-images.githubusercontent.com/83373378/123807091-8d8a4600-d8bd-11eb-84db-a4423a8b5c2b.png">
[147r can't toggle orange boy (staging).zip](https://github.com/DDMAL/Neon/files/6733760/147r.can.t.toggle.orange.boy.staging.zip)

**Comment by JoyfulGen** [comment]
I take back what I said! The devs did something (don't know what, but I'm grateful) and it works! And as a bonus, when ungrouping a neume that contains a ligature, the ligature remains, which is fantastic. Here's the same neume as yesterday to demonstrate:
<img width="906" alt="147r ungrouped neume - ligature remains" src="https://user-images.githubusercontent.com/83373378/124016775-ffdd5200-d9b3-11eb-8efc-a07d51975426.png">
[147r neume ungrouped oblique remains (staging) .zip](https://github.com/DDMAL/Neon/files/6743389/147r.neume.ungrouped.oblique.remains.staging.zip)

**Comment by annamorphism** [comment]
this issue is back! Seems like previously ligated neumes (i.e. where ligated="false") only want to ligate with other previously ligated neumes, but not any others (i.e. that don't say either ligated =true or false in the file). Likewise neume components that haven't ever been ligated will only ligate with each other, and not components from a previous ligature.

**Comment by annamorphism** [comment]
Fixed in most recent version.

**Comment by annamorphism** [comment]
It's baaaack! Einsiedeln 40v: 
![image](https://user-images.githubusercontent.com/67451875/157347026-5c4b1d39-ea7b-45d8-8ecd-1a312d02dfaa.png)
The neumes in question LOOK like you can toggle them: 
![image](https://user-images.githubusercontent.com/67451875/157347400-0e37fe59-d55b-4059-b9e4-2f43300b6c02.png)
But because one is "false", you can't....
![image](https://user-images.githubusercontent.com/67451875/157347472-2be731c4-94a4-46a3-8aff-ea714f87ee4c.png)

**Comment by JoyfulGen** [comment]
I think this is related to https://github.com/DDMAL/Neon/issues/777. That "false" appears when you try to toggle two `nc`'s that aren't both puncta, as is the case in your example. I think when https://github.com/DDMAL/Neon/issues/777 is fixed, this should be fixed too...?
