### ISSUE TITLE
Feature request: to have the outline of invisible bounding boxes appear when I select their corresponding syllable

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#749]
This request is related to issue https://github.com/DDMAL/Neon/issues/656

In the issue linked above, we determined that if a bounding box (BB) is "flipped," so if its upper and lower or left and right coordinates are inverted, it disappears. Once the BB is flipped, selecting its corresponding syllable doesn't make it appear. The only way to find it again is to click and drag over the exact spot the invisible BB is hiding. That makes the outline appear, which allows you to drag the edge back and un-flip the BB. Here's a demo:

https://user-images.githubusercontent.com/83373378/148950017-4fa93602-d855-4700-8d46-6a3216936c3e.mov

In this situation, I could easily find the invisible BB again, because I created it, so I knew exactly where it was. However, it often happens that a BB is already invisible (this happens if the BBs of the neume components are in the wrong order before they're grouped; this is illustrated in the little video at the end of my comment). When this happens, I generally can't find it, because I have no idea where it is. The only solution then is to delete the neume and input it back in. 

My request therefore is for the outline of an invisible BB to appear when one selects its corresponding syllable. The BB itself can stay uncoloured, to distinguish it from a BB that's going the right way--having the outline is sufficient to a) locate it and b) flip it back.

Annex A: Demo of the resulting BB being invisible when I group two neume components with BBs in the wrong order.

https://user-images.githubusercontent.com/83373378/148954590-12c93acc-c6c3-4d87-b612-b9d2c78b83e2.mov

**Comment by yinanazhou** [comment]
Hi again @JoyfulGen, I have pushed the changes for the `y` coordinate of `bbox`. Now the `bbox` should not be flipped if the order is not the same as `NC` order or the `bbox`es are not vertically aligned. Next, I will work on the outline of flipped `bbox`. Please let me know if the changes function well. Thank you!

**Comment by JoyfulGen** [comment]
My first tests indicate that the fix works perfectly! I'm now correcting an entire folio to see how it holds up; I'll keep you updated.

**Comment by yinanazhou** [comment]
Hiiii @JoyfulGen, Gaby and I have fixed the flipped bbox issue. Please let me know if it works!

**Comment by JoyfulGen** [comment]
It does work! I've tried flipping the bounding box around in all sorts of ways and it appears that the invisibility issue is completely gone; the box is always visible, no matter what I do! As usual I'll correct a complete folio and keep you updated.

**Comment by JoyfulGen** [comment]
The flipped bounding box issue is back!! And it appears the be the same: if two bounding boxes are in the wrong order when their corresponding syllables are merged, the resulting bbox is invisible. Demo:

https://user-images.githubusercontent.com/83373378/185406973-678c5219-0947-4cf5-b6f0-7d90366e8478.mov

This issue was for sure fixed, but it started reappearing recently. @yinanazhou, was something about the behaviour of bounding boxes changed?

**Comment by JoyfulGen** [comment]
It's been fixed! Re-closing the issue now.
