### ISSUE TITLE
When clicking on a ligature, option to "group neume components" appears (but not "toggle")

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#797]
This issue may be related to https://github.com/DDMAL/Neon/issues/727.

When one clicks on a ligature in Neon, the option appears to "Toggle ligature," which separates the ligature into its two puncta. However, it sometimes happens that when I click on a ligature, I only get a "Group neume components" option (that's what leads to https://github.com/DDMAL/Neon/issues/727). 

Here's what's weird though: as I was trying to find the difference between ligatures that give the option to group and ligatures that give the option to toggle, I realized that the **same** ligature can do both, seemingly at random. Here's the MEI of a ligature (Einsie 253r) that only gave me the "Group neume components" option:

<img width="875" alt="253r group option" src="https://user-images.githubusercontent.com/83373378/164486502-cdab0b8b-266c-439d-8145-316b1f2b614b.png">

And here's the MEI of that same ligature when I clicked on it again (without having done anything else) and it gave me a "Toggle ligature" option:

<img width="863" alt="253r toggle option" src="https://user-images.githubusercontent.com/83373378/164486673-8aaf9a50-f9c9-4f3e-aa5a-1f06cc8ffa9e.png">

As far as I can tell, they're identical! So what's causing the different options to appear, and how can they appear for the same ligature?

I'll keep looking, but for now that's all I've got. I am bamboozled.

**Comment by JoyfulGen** [comment]
Here is proof: same lig, two options.
https://user-images.githubusercontent.com/83373378/164487805-b0273542-45ab-41b2-8910-b44be3039b91.mov

**Comment by yinanazhou** [comment]
I might found something. When you drag select the oblique, the "group neume components" option will show up.

**Comment by JoyfulGen** [comment]
> I might found something. When you drag select the oblique, the "group neume components" option will show up.

I agree! I've just tested it and I get the same result.

**Comment by JoyfulGen** [comment]
Small update: now that https://github.com/DDMAL/Neon/issues/727 is fixed this is much less of a pressing issue. Even if we do click on "group neume components," nothing happens, so it doesn't really matter. It's still a bit confusing though! And if the user doesn't know, it can be frustrating to drag and click several times and never get the "toggle ligature" option.

**Comment by chetbae** [comment]
1. when drag-selecting selects just a ligature, `group neume components` appears instead of `toggle ligature`
2. same goes for when click-selecting within the bounding box of a ligature but not on the SVG element (symbol)

Working on a fix to make sure that `toggle ligature` is presented when only a ligature is selected.

**Comment by chetbae** [comment]
[clip 1](https://user-images.githubusercontent.com/48145854/167714594-b175ee0f-7e58-4383-9b97-12700bb5b6c9.mov)
[clip 2](https://user-images.githubusercontent.com/48145854/167714599-c2a642b0-a175-4d52-8932-c3ddab016f3e.mov)

@JoyfulGen is this the expected behaviour?

**Comment by JoyfulGen** [comment]
@chetbae yes it is!! That looks totally perfect, thank you!

**Comment by annamorphism** [comment]
I agree with @JoyfulGen !

**Comment by JoyfulGen** [comment]
I tested the changes and, when selecting a ligature, the option to "toggle ligature" always appears, regardless of how you selected it. This is great! Also, when drag clicking on two puncta, the option appears to "toggle ligature" as well. There's just one little fix I'd like to ask for:

Another way of selecting two puncta is to click on one and then ctrl/cmd-click on the other. At the moment, if I select two puncta this way I only get the "group neume components" option. @chetbae and @yinanazhou, would it be possible to give the "toggle ligature" option when selecting puncta this way too?

**Comment by chetbae** [comment]
hey @JoyfulGen this newest pr should fix the problem for 2 puncta!

**Comment by JoyfulGen** [comment]
Just tested it! It looks like it works if I select them from bottom to top, but if I select them from top to bottom I still get the "group neume components" option. Demo:

https://user-images.githubusercontent.com/83373378/168333442-91a83336-178f-4a0b-91c9-1ed23e050208.mov
