### ISSUE TITLE
The fact that you can't group non-consecutive neumes adds steps to correction process

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon#966]
It's easiest to explain this with a demo:
- In the video, the green neume was in the original MEI--two of the puncta are blue and orange because I added them
- When I ungroup the green neume, those neume components are still part of the same syllable, so Neon has to understand them as being consecutive. This means that the two puncta I added are appearing at the end of that syllable, so Neon won't let me group them.
- To do so, I have to go to syllable highlight, ungroup the syllable, and then come back and group the neumes as I want.

https://user-images.githubusercontent.com/83373378/185908510-f900fd71-28e5-491d-ae70-cd06b06e032e.mov
 
This sort of situation happens quite often. Would it be ok to allow the user to group non-consecutive neumes, even if it's counterintuitive? @yinanazhou @cadagong

**Comment by cadagong** [comment]
Hi @JoyfulGen! I'm taking a look at this issue right now. I did some playing around myself just to understand the problem better. If I understand correctly, the objective is to take two (or more) neumes that are originally in separate syllables and merge all the neumes into a single neume in the same syllable.

If this is the case, I could be wrong, but it looks like the desired outcome can be achieved by first merging the three syllables, then switching to selection by Neume Component, and, grouping the desired components into a single Neume.

Please let me know if this could be a potential solution/if I understood the problem correctly. I will keep exploring the issue in the meantime :))

**Comment by JoyfulGen** [comment]
Hey @cadagong, you have understood the issue correctly and your fix works! I do still feel like it's adding an extra step which the user might have to undo later (if the syllables need to be separated, for example). Also, I found a couple of minor issues when I replicated your suggested series of actions:

- If I want to group new neume components with other neume components that are already part of a bigger neume (as I do in the video below), the "g" toggle doesn't work.
- When I regroup the neume components in the middle of the neume, the resulting neume and the neume after that are in the wrong order (should be blue-orange-pink). I have to ungroup the syllable to make the neumes appear in the correct order. You can see that in the video below.

https://user-images.githubusercontent.com/83373378/188871676-3bde77d5-6180-4d56-820a-81e00e6d138c.mov

**Comment by JoyfulGen** [comment]
I've been exploring more and I've found another slight inconvenience with your solution. The problem is that, when highlighting by neume, you can't see syllables, which means you can't see which neumes are grouped together. That makes it difficult to know which neumes you have to group to be able to group the neume components you want. In this situation, for example:
<img width="233" alt="Screen Shot 2022-09-07 at 2 27 10 PM" src="https://user-images.githubusercontent.com/83373378/188878498-634fb656-f43f-45fa-a90c-efc82e7c34a0.png">
I want to group the neume components in the blue box. However, I can't, because they're not consecutive, so Neon won't let me group them. Using your solution, my first instinct would be to group those three components with the neume following (the pink one). However, that also doesn't work, because they're not consecutive either. It's only by highlighting by syllable that I can see that the third neume is also part of the syllable, so I have to include it in my selection to group the neumes. 
<img width="261" alt="Screen Shot 2022-09-07 at 2 27 35 PM" src="https://user-images.githubusercontent.com/83373378/188878865-9d7407ac-30e9-4801-adf9-67f65c73188d.png">
Does that make sense? I'll be happy to meet with you to explain this in person if that's simpler.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue. Please let me know if it works. Thanks!

**Comment by JoyfulGen** [comment]
It works perfectly! I like that you still can't group neumes on different staves, only on the same staff. This honestly saves a lot of time; thank you!
